### ISSUE TITLE
401 Authentication Required

### ISSUE THREAD

**Issue by Nevexo** [stunndard/goicy#6]
We have an Icecast2 server and are trying to use goicy as a failover AutoDJ server
This is my goicy ini file's server definition:

`
[server]

; server type
; must be either 'icecast' or 'shoutcast'
server = icecast

; icecast/shoutcast host and port
host = ic.tmw.media
port = 9978

; icecast mountpoint
; valid only for icecast servers
; has no meaning if server is 'shoutcast'
mount = live

; icecast/shoutcast source password
password = [redacted]

; how many times goicy should try to reconnect to a server before giving up
connectionattempts = 5`

But I get a 401 error. Does goicy support Icecast2?

**Comment by MrShoenel** [comment]
I am using it with Icecast v2.4.3 since months.. so, yes! :) Here's one of my ini's:

``
[server]

; server type
; must be either 'icecast' or 'shoutcast'
server = icecast

; icecast/shoutcast host and port
host = 127.0.0.1
port = 8000

; icecast mountpoint
; valid only for icecast servers
; has no meaning if server is 'shoutcast'
mount = listen/MyRadioStation

; icecast/shoutcast source password
password = hackme

; how many times goicy should try to reconnect to a server before giving up
connectionattempts = 5

;------

[stream]

; internal name (ID) that should also correspond to the service's name (systemd)
nameinternal = MyRadioStation

; stream type
; must be 'file' or 'ffmpeg'
streamtype = ffmpeg

; stream format
; mp3 or aac
format = aac

; stream name
name = MyRadioStation

; stream description
description = MyRadioStation description

; stream url
url = http://example.com/MyRadioStation

; stream genre
genre = 80s, 90s, Rock, Pop

; set public to 1 to publish your stream in icecast/shoutcast
; yp directory, 0 otherwise
public = 0

;------

[ffmpeg]

; path to the ffmpeg executable
; can be just ffmpeg or ffmpeg.exe if ffmpeg is in PATH
; ffmpeg should be configured with --enable libfdk_aac
ffmpeg = /opt/ffmpeg/ffmpeg

; sample rate in Hz
samplerate = 48000

; channels
; 1 = mono, 2 stereo
channels = 2

; ffmpeg bitrate for MPEG or AAC
bitrate = 32000

; AAC profile
; must be 'lc', 'he', 'hev2'
; valid only for stream format AAC
aacprofile = hev2

;------

[playlist]

; playlist type. must be 'internal' or 'lua'
playlisttype = internal

; playlist file.
; if playlisttype is 'internal', then playlist is a file
; with track file names, one file on a string
; if playlisttype is 'lua', then playlist is a lua script with some predefined
; functions that are called by goicy
playlist = /etc/radio/MyRadioStation.playlist

; random play order flag, 1 for random, 0 for sequential
; only valid if playlisttype is 'internal'
; has no meaning if playlisttype is 'lua'
playrandom = 0

;-------

[misc]

; daemon mode, works on linux only.
; 1 to enable, 0 to disable
; ignored totally on windows
daemon = 0

; pid file for the goicy daemon. works on linux only
; ignored totally on windows
pidfile = /var/run/goicy_MyRadioStation.pid

; send-ahead buffer size in seconds
buffersize = 4

; whether to update stream metadata from ID3 tags.
; 1 to enable, 0 to disable updating.
updatemetadata = 1

; script file
;script = script.lua

; nowplay temporary file. used to resume play from the same track
; between subsequent goicy runs.

; nowplay temporary file. used to resume play from the same track
; between subsequent goicy runs.
;npfile = np.tmp

; goicy log file
logfile = /dev/null

; logging verbosity
; set to 0 for normal log, or 1 to be more verbose
loglevel = 0

``

**Comment by Nevexo** [comment]
@MrShoenel Thanks for your reply - I sat and compared our configs for a good 10 minutes before noticing the IC2 stream password isn't the same as the source password - I feel stupid. Thanks anyway :)
